### ISSUE TITLE
Interview with district staff and district managers involved in the 4 FLP pilot projects

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fop#27]
Describe the task
Continue to conduct interviews with district staff and district managers

Acceptance Criteria

- [ ] conduct the interviews
- [ ] notes are recorded on mural board
- [ ] notes transcribed

**Comment by gormless87** [comment]
@OlgaLiber2  - can you provide and update on this issue? Have any of the AC been met? Perhaps we can meet tomorrow or next week to discuss how the work can be broken out into separate tasks so they can be completed within a single sprint.
