### ISSUE TITLE
Investigate if we can use any existing components for FOP

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fop#28]
Investigate if any of the 3 main components for FOP can be adapted from existing applications: 
- are there existing widgets we can use? 

**1. form** 
Can we use CHEFS?
link to mural board: https://app.mural.co/t/climatechange4363/m/climatechange4363/1701281253599/1443418d3e664f800fe78f4f48fdbbbc608bc63e?sender=u84301558fa490f89e6792901

**2. spatial + comments** 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be432c73c72e0896d99fdf9f70d2092104c9fbf4/comments%20on%20a%20spatial%20map.PNG)

**3. Drag and drop Kanban board** 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a0f386f3fb1cd48eda311e704e704571b978fd4/Capture-comments.PNG)

**Comment by OlgaLiber2** [comment]
@basilv Here's the first low-fidelity version of a submission form. I'll have more iterations but it's a starting point. We can review form requirements together if you want.  [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29hQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a22e51987b333e98b6c1b4076cf252753388538/FOP-submission-formv1.png)

UX principles to incorporate: 
- **stepped form:** 
---> form sections do not have to be filled in a liner way. 
---> user can save the form at any point and come back to it later

- **spatial validation:**
---> when the user uploads shape files, they can the polygons on the map right away (before they submit the form)

**Comment by basilv** [comment]
Hmm, I can't see that image.

**Comment by OlgaLiber2** [comment]
@basilv try the mural board link https://app.mural.co/t/climatechange4363/m/climatechange4363/1701281253599/1443418d3e664f800fe78f4f48fdbbbc608bc63e?sender=u84301558fa490f89e6792901

**Comment by OlgaLiber2** [comment]
CHEFS is out because we can't do spatial, and it's central for a FOP submission

**Comment by basilv** [comment]
1. CHEFS very likely won't meet our needs - we can build forms in whatever stack we are using
2. Leaflet supports spatially-aware clicks that can be used to create comments for a specific location
3. There are multiple javascript libraries for doing drag&drop task boards. See e.g. https://dev.to/bryntum/best-drag-and-drop-libraries-for-frontend-developers-39d5

**Comment by OlgaLiber2** [comment]
@basilv  🙌🙌 for point 3. Seems like it will be a fairly straight forward implementation.

And point 2 also seems possible.
